version: '3.8'
services:
  octoprint:
      container_name: OctoPrint_PrintBot
      image: eriklou/octoprint:latest
      stdin_open: true
      tty: true
      hostname: PrintBot
      restart: unless-stopped
      ports:
        - "800:80"
      volumes:
        - /home/eriklou/rigs/ender3Pro/octoprint:/octoprint
      environment:
        - ENABLE_MJPG_STREAMER=true
        - MJPG_STREAMER_INPUT=-n -r 1280x720 -f 30
      devices:
      #Printer Port
        - /dev/ttyACM0:/dev/ttyACM0
      #Webcam port
        - /dev/video0:/dev/video0
        
      logging:
        driver: syslog
        options:
          syslog-address: "tcp://192.168.1.9:514"

  ####
  # uncomment if you wish to edit the configuration files of octoprint
  # refer to docs on configuration editing for more information
  ####

  #config-editor:
  #  image: linuxserver/code-server
  #  ports:
  #    - 8443:8443
  #  depends_on:
  #    - octoprint
  #  restart: unless-stopped
  #  environment:
  #    - PUID=0
  #    - GUID=0
  #    - TZ=America/Chicago